"""
Test Objective Functions for globtimpostprocessing Fixtures

These functions reproduce the objective functions used to generate test fixtures.
They match the data in critical_points_raw_deg_*.csv files.

Generated by: globtimcore/test/fixtures/generate_postprocessing_fixtures.jl
Generated at: 2025-11-24 13:25:11
"""

"""
    deuflhard_4d_fixture(p::Vector{Float64}) -> Float64

4D Deuflhard test function - composition of two 2D Deuflhard functions.
This matches the globtimcore function `Deuflhard_4d`.

# Domain
[-1.2, 1.2]^4

# Mathematical Form
```
f(p) = Deuflhard(p[1:2]) + Deuflhard(p[3:4])

where Deuflhard(x,y) = (exp(x² + y²) - 3)² + (x + y - sin(3(x + y)))²
```

# Properties
- Multiple local minima
- Global minimum at approximately (0, 0, 0, 0)
- Well-conditioned for optimization
- Fast to evaluate (no ODE solving)

# Example
```julia
# Evaluate at origin (near global minimum)
f_val = deuflhard_4d_fixture([0.0, 0.0, 0.0, 0.0])

# Use in refinement test
config = ode_refinement_config()
refined = refine_critical_point(deuflhard_4d_fixture, initial_point, config)
```
"""
function deuflhard_4d_fixture(p::AbstractVector)
    return deuflhard_2d(p[1:2]) + deuflhard_2d(p[3:4])
end

"""
    deuflhard_2d(xx::AbstractVector) -> Float64

2D Deuflhard function component.

# Mathematical Form
```
f(x, y) = (exp(x² + y²) - 3)² + (x + y - sin(3(x + y)))²
```

# Properties
- Global minimum at approximately (0, 0)
- Multiple local minima in domain [-1.2, 1.2]²
- Smooth and differentiable everywhere
"""
function deuflhard_2d(xx::AbstractVector)
    term1 = (exp(xx[1]^2 + xx[2]^2) - 3)^2
    term2 = (xx[1] + xx[2] - sin(3 * (xx[1] + xx[2])))^2
    return term1 + term2
end
