"""
    GlobtimPostProcessing.jl

Label-aware post-processing framework for GlobTim experiment results.

This package provides adaptive analysis that automatically discovers and processes
experimental data based on tracking labels generated by globtimcore experiments.

# Main Features
- **Label-driven processing**: Reads `enabled_tracking` metadata from experiments
- **Adaptive statistics**: Computes only relevant statistics based on available data
- **Campaign aggregation**: Analyzes multiple experiments as coherent campaigns
- **Report generation**: Creates publication-ready analysis reports

# Typical Workflow
```julia
using GlobtimPostProcessing

# Single experiment
results = load_experiment_results("path/to/experiment")
stats = compute_statistics(results)
report = generate_report(results, stats)

# Multi-experiment campaign
campaign = load_campaign_results("path/to/campaign_directory")
campaign_stats = analyze_campaign(campaign)
```

Author: GlobTim Team
Created: October 2025
"""
module GlobtimPostProcessing

using JSON
using JSON3
using DataFrames
using Statistics
using LinearAlgebra
using Printf
using Dates
using CSV
using ProgressMeter

# Core functionality exports
export load_experiment_results, load_campaign_results
export compute_statistics, compute_statistics_for_label
export analyze_campaign, aggregate_campaign_statistics
export generate_report, generate_campaign_report
export save_report, generate_and_save_report, save_campaign_report
export ExperimentResult, CampaignResults
export PlotBackend, Interactive, Static
export create_experiment_plots, create_campaign_comparison_plot, create_single_plot, save_plot

# Phase 2: Batch processing exports
export batch_analyze_campaign, load_campaign_with_progress
export aggregate_campaign_statistics_with_progress, batch_analyze_campaign_with_progress

# VegaLite + Tidier exports
export campaign_to_dataframe, create_interactive_campaign_explorer
export campaign_to_tidy_dataframe, compute_campaign_summary_stats
export compute_convergence_analysis, compute_efficiency_metrics
export compute_parameter_sensitivity, filter_best_experiments
export pivot_metrics_longer, add_comparison_baseline
export create_convergence_dashboard, create_parameter_sensitivity_plot
export create_multi_metric_comparison, create_efficiency_analysis
export create_outlier_detection_plot, create_baseline_comparison

# Define types first
"""
    ExperimentResult

Container for a single experiment's results and metadata.

# Fields
- `experiment_id::String`: Unique identifier for the experiment
- `metadata::Dict{String, Any}`: Experiment configuration and parameters
- `enabled_tracking::Vector{String}`: Labels of tracked quantities
- `tracking_capabilities::Vector{String}`: All possible tracking labels for this experiment
- `critical_points::Union{DataFrame, Nothing}`: Critical points DataFrame
- `performance_metrics::Union{Dict, Nothing}`: Timing and resource usage
- `tolerance_validation::Union{Dict, Nothing}`: Numerical validation results
- `source_path::String`: Path to experiment output directory
"""
struct ExperimentResult
    experiment_id::String
    metadata::Dict{String, Any}
    enabled_tracking::Vector{String}
    tracking_capabilities::Vector{String}
    critical_points::Union{DataFrame, Nothing}
    performance_metrics::Union{Dict, Nothing}
    tolerance_validation::Union{Dict, Nothing}
    source_path::String
end

"""
    CampaignResults

Container for multi-experiment campaign results.

# Fields
- `campaign_id::String`: Unique identifier for the campaign
- `experiments::Vector{ExperimentResult}`: Individual experiment results
- `campaign_metadata::Dict{String, Any}`: Campaign-level configuration
- `collection_timestamp::DateTime`: When results were collected
"""
struct CampaignResults
    campaign_id::String
    experiments::Vector{ExperimentResult}
    campaign_metadata::Dict{String, Any}
    collection_timestamp::DateTime
end

# Include submodules (after type definitions)
include("ResultsLoader.jl")
include("LabelDispatcher.jl")
include("StatisticsCompute.jl")
include("ReportGenerator.jl")
include("TableFormatting.jl")   # Terminal-friendly table formatting
include("CampaignAnalysis.jl")
include("Plotting.jl")
include("BatchProcessing.jl")  # Phase 2: Batch processing functionality
include("VegaPlotting.jl")      # VegaLite + Tidier interactive visualizations

end # module GlobtimPostProcessing
