"""
    GlobtimPostProcessing.jl

Label-aware post-processing framework for GlobTim experiment results.

This package provides adaptive analysis that automatically discovers and processes
experimental data based on tracking labels generated by globtim experiments.

# Main Features
- **Label-driven processing**: Reads `enabled_tracking` metadata from experiments
- **Adaptive statistics**: Computes only relevant statistics based on available data
- **Campaign aggregation**: Analyzes multiple experiments as coherent campaigns
- **Report generation**: Creates publication-ready analysis reports

# Typical Workflow
```julia
using GlobtimPostProcessing

# Single experiment
results = load_experiment_results("path/to/experiment")
stats = compute_statistics(results)
report = generate_report(results, stats)

# Multi-experiment campaign
campaign = load_campaign_results("path/to/campaign_directory")
campaign_stats = analyze_campaign(campaign)
```

Author: GlobTim Team
Created: October 2025
"""
module GlobtimPostProcessing

using JSON
using JSON3
using DataFrames
using Statistics
using LinearAlgebra
using Printf
using Dates
using CSV
using ProgressMeter
using StatsBase
using Optim  # Critical point refinement
using ForwardDiff  # Gradient computation for validation (algebraic objectives)
using FiniteDiff   # Numerical gradients for ODE-based objectives
using PrettyTables  # Rich terminal table formatting
using JLD2          # Tree serialization

# Core functionality exports
export load_experiment_results, load_campaign_results
export compute_statistics, compute_statistics_for_label
export analyze_campaign, aggregate_campaign_statistics
export generate_report, generate_campaign_report
export save_report, generate_and_save_report, save_campaign_report
export ExperimentResult, CampaignResults

# Unified pipeline exports (January 2026)
# Re-exported from UnifiedPipeline module for convenience
export postprocess  # Interactive unified TUI
export load_experiment  # Unified loader with type detection
export ExperimentType, LV4DType, DeuflhardType, FitzHughNagumoType, UnknownType
export LV4D, DEUFLHARD, FITZHUGH_NAGUMO, UNKNOWN
export detect_experiment_type, type_name
export BaseExperimentData, get_base
export experiment_id, experiment_path, experiment_type
export degree_results, critical_points, has_critical_points, available_degrees

# Phase 2: Batch processing exports
export batch_analyze_campaign, load_campaign_with_progress
export aggregate_campaign_statistics_with_progress, batch_analyze_campaign_with_progress


# Parameter recovery exports (Issue #7)
export param_distance, load_experiment_config, load_critical_points_for_degree
export compute_parameter_recovery_stats, generate_parameter_recovery_table, has_ground_truth

# Quality diagnostics exports (Issue #7, Phase 3)
export load_quality_thresholds
export check_l2_quality
export detect_stagnation, StagnationResult
export check_objective_distribution_quality, ObjectiveDistributionResult

# Table formatting exports (display functions)
export format_metrics_table, format_compact_summary, format_grouped_metrics

# Display helpers (shared formatting for terminal output)
export fmt_sci, fmt_time, fmt_pct, print_section, styled_table
export Highlighter  # re-exported from PrettyTables for demo scripts

# Experiment display (pipeline orchestration + display functions)
export print_experiment_header, print_poly_summary_table
export compute_degree_capture_results
export DegreeAnalysisResult, run_degree_analyses, print_degree_analysis_table
export build_degree_convergence_info
export BestEstimate, find_best_estimate, find_best_raw_estimate
export print_parameter_recovery_table, print_recovery_verdict
export print_best_minimum, print_error_banner

# Critical point classification exports
export classify_critical_point, classify_all_critical_points!
export count_classifications, find_distinct_local_minima
export get_classification_summary

# Landscape fidelity exports
export check_objective_proximity, estimate_basin_radius, check_hessian_basin
export assess_landscape_fidelity, batch_assess_fidelity
export ObjectiveProximityResult, HessianBasinResult, LandscapeFidelityResult

# Critical point refinement exports
export RefinementConfig, ode_refinement_config
export refine_experiment_results, refine_critical_points
export RefinedExperimentResult, RefinementResult
export load_raw_critical_points, save_refined_results, RawCriticalPointsData
export refine_critical_point, refine_critical_points_batch
export print_refinement_summary, print_comparison_table
export RefinementDistanceResult, compute_refinement_distances

# Gradient validation exports
export compute_gradient_norms, compute_gradient_norm
export validate_critical_points, add_gradient_validation!
export GradientValidationResult

# Newton-based critical point refinement exports
export CriticalPointRefinementResult
export refine_to_critical_point, refine_to_critical_points

# Capture analysis exports
export KnownCriticalPoints, CaptureResult
export compute_capture_analysis, missed_critical_points
export print_capture_summary, print_degree_capture_convergence
export build_known_cps_from_2d_product, build_known_cps_from_refinement
export DegreeConvergenceInfo, print_degree_convergence_summary
export CaptureVerdict, compute_capture_verdict, print_capture_verdict

# Valley walking exports (positive-dimensional minima tracing)
export ValleyWalkConfig, ValleyTraceResult
export detect_valley, trace_valley, trace_valleys_from_critical_points
export walk_newton_projection, walk_predictor_corrector

# Experiment parameter index exports (January 2026)
# Note: Consolidated into Pipeline.PipelineRegistry - re-exported from Pipeline module
export ExperimentParams, ExperimentEntry, ParameterCoverage
export extract_params_from_name, compute_params_hash, params_hash
export has_experiment_with_params, get_experiments_by_params
export get_experiments_for_params, get_parameter_coverage
export print_coverage_matrix, print_query_results
export get_unique_params, list_unique_params, get_missing_params

# Experiment parameter index TUI
export experiments  # Interactive TUI for parameter index
export select_experiments  # Interactive selection returning ExperimentFilter

# Subdivision tree analysis exports
export load_subdivision_tree, analyze_subdivision_tree, SubdivisionTreeStats
export tree_leaves_to_dataframe, tree_depth_summary
export print_subdivision_tree_report
export compare_subdivision_trees, print_tree_comparison_table

# Enhanced analysis exports (moved from globtim - January 2026)
# Statistical table types
export StatisticalTable, RobustStatistics, ConditionNumberAnalysis, ValidationResults
export HessianNormTable, ConditionNumberTable, ComprehensiveStatsTable
# Statistical computation functions
export compute_robust_statistics, compute_condition_number_analysis
export perform_mathematical_validation, compute_type_specific_statistics
# Table rendering functions
export render_table, render_console_table, render_comparative_table
# High-level analysis functions
export display_statistical_table, export_analysis_tables
export create_statistical_summary, quick_table_preview

# Define types first
"""
    ExperimentResult

Container for a single experiment's results and metadata.

# Fields
- `experiment_id::String`: Unique identifier for the experiment
- `metadata::Dict{String, Any}`: Experiment configuration and parameters
- `enabled_tracking::Vector{String}`: Labels of tracked quantities
- `tracking_capabilities::Vector{String}`: All possible tracking labels for this experiment
- `critical_points::Union{DataFrame, Nothing}`: Critical points DataFrame
- `performance_metrics::Union{Dict, Nothing}`: Timing and resource usage
- `tolerance_validation::Union{Dict, Nothing}`: Numerical validation results
- `source_path::String`: Path to experiment output directory
"""
struct ExperimentResult
    experiment_id::String
    metadata::Dict{String, Any}
    enabled_tracking::Vector{String}
    tracking_capabilities::Vector{String}
    critical_points::Union{DataFrame, Nothing}
    performance_metrics::Union{Dict, Nothing}
    tolerance_validation::Union{Dict, Nothing}
    source_path::String
end

"""
    CampaignResults

Container for multi-experiment campaign results.

# Fields
- `campaign_id::String`: Unique identifier for the campaign
- `experiments::Vector{ExperimentResult}`: Individual experiment results
- `campaign_metadata::Dict{String, Any}`: Campaign-level configuration
- `collection_timestamp::DateTime`: When results were collected
"""
struct CampaignResults
    campaign_id::String
    experiments::Vector{ExperimentResult}
    campaign_metadata::Dict{String, Any}
    collection_timestamp::DateTime
end

# Include submodules (after type definitions)
include("display_helpers.jl")  # Shared formatting: fmt_sci, fmt_time, fmt_pct, print_section
include("ResultsLoader.jl")
include("LabelDispatcher.jl")
include("StatisticsCompute.jl")
include("ReportGenerator.jl")
include("TableFormatting.jl")   # Terminal-friendly table formatting
include("CampaignAnalysis.jl")
include("BatchProcessing.jl")  # Phase 2: Batch processing functionality
include("ParameterRecovery.jl")  # Issue #7: Parameter recovery analysis
include("QualityDiagnostics.jl")  # Issue #7, Phase 3: Quality diagnostics
include("CriticalPointClassification.jl")  # Critical point classification based on Hessian eigenvalues
include("LandscapeFidelity.jl")  # Landscape fidelity: polynomial vs objective basin assessment

# Critical point refinement (moved from globtim - 2025-11-22)
include("refinement/core_refinement.jl")  # Core refinement algorithms
include("refinement/config.jl")           # RefinementConfig struct
include("refinement/gradient_validation.jl")  # Gradient norm validation (before io.jl - defines GradientValidationResult)
include("refinement/newton_refinement.jl")      # Newton-based critical point refinement (∇f=0)
include("refinement/capture_analysis.jl")      # Capture analysis for known critical points
include("refinement/io.jl")               # Load/save utilities
include("refinement/api.jl")              # High-level API

# Experiment display (pipeline orchestration + display functions)
include("experiment_display.jl")

# Valley walking (positive-dimensional minima tracing)
include("ValleyWalking.jl")

# Pipeline module (experiment discovery and orchestration - GC-08)
# Contains the canonical experiment registry (PipelineRegistry) with parameter indexing
include("pipeline/Pipeline.jl")

# Re-export parameter index symbols from Pipeline module
using .Pipeline: ExperimentParams, ExperimentEntry, ParameterCoverage
using .Pipeline: extract_params_from_name, compute_params_hash, params_hash
using .Pipeline: has_experiment_with_params, get_experiments_by_params
using .Pipeline: get_experiments_for_params, get_parameter_coverage
using .Pipeline: print_coverage_matrix, print_query_results
using .Pipeline: get_unique_params, list_unique_params, get_missing_params

# Experiment parameter index TUI
include("ExperimentIndexTUI.jl")

# Subdivision tree analysis (adaptive subdivision postprocessing - January 2026)
include("SubdivisionTreeAnalysis.jl")

# Enhanced analysis (moved from globtim - January 2026)
# Statistical tables, condition number analysis, and mathematical validation
include("EnhancedAnalysis.jl")

# Unified pipeline module (type-aware experiment loading - January 2026)
# MUST be included before LV4DAnalysis which depends on it
include("unified/UnifiedPipeline.jl")

# Re-export unified pipeline symbols
using .UnifiedPipeline: postprocess, load_experiment
using .UnifiedPipeline: ExperimentType, LV4DType, DeuflhardType, FitzHughNagumoType, UnknownType
using .UnifiedPipeline: LV4D, DEUFLHARD, FITZHUGH_NAGUMO, UNKNOWN
using .UnifiedPipeline: detect_experiment_type, type_name
using .UnifiedPipeline: BaseExperimentData, get_base
using .UnifiedPipeline: experiment_id, experiment_path, experiment_type
using .UnifiedPipeline: degree_results, critical_points, has_critical_points, available_degrees

# LV4D analysis module (unified LV4D post-processing - January 2026)
include("lv4d/LV4DAnalysis.jl")

# NOTE: Plotting functionality has been moved to GlobtimPlots package
# To create visualizations, use:
#     using GlobtimPostProcessing
#     using GlobtimPlots
#     plots = create_experiment_plots(experiment_result)
#
# GlobtimPlots provides:
# - create_experiment_plots, create_campaign_comparison_plot, create_single_plot, save_plot
# - PlotBackend types: Interactive, Static
# - generate_experiment_labels
#
# This separation ensures GlobtimPostProcessing remains a pure data analysis package
# without heavy plotting dependencies.

end # module GlobtimPostProcessing
